project_id = "rwyollwudpggygxcsndh"

[functions.generate-recommendations]
verify_jwt = true

[functions.meal-planning-chat]
verify_jwt = true

[functions.scan-document]
verify_jwt = true

[functions.fill-document]
verify_jwt = true